# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/diabolo/delivery/Raytracer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/diabolo/delivery/Raytracer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/diabolo/delivery/Raytracer/CMakeFiles /home/diabolo/delivery/Raytracer//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/diabolo/delivery/Raytracer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named beton

# Build rule for target.
beton: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 beton
.PHONY : beton

# fast build rule for target.
beton/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/beton.dir/build.make CMakeFiles/beton.dir/build
.PHONY : beton/fast

src/raytracer/camera.o: src/raytracer/camera.cpp.o
.PHONY : src/raytracer/camera.o

# target to build an object file
src/raytracer/camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/beton.dir/build.make CMakeFiles/beton.dir/src/raytracer/camera.cpp.o
.PHONY : src/raytracer/camera.cpp.o

src/raytracer/camera.i: src/raytracer/camera.cpp.i
.PHONY : src/raytracer/camera.i

# target to preprocess a source file
src/raytracer/camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/beton.dir/build.make CMakeFiles/beton.dir/src/raytracer/camera.cpp.i
.PHONY : src/raytracer/camera.cpp.i

src/raytracer/camera.s: src/raytracer/camera.cpp.s
.PHONY : src/raytracer/camera.s

# target to generate assembly for a file
src/raytracer/camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/beton.dir/build.make CMakeFiles/beton.dir/src/raytracer/camera.cpp.s
.PHONY : src/raytracer/camera.cpp.s

src/raytracer/lights/ambientLight.o: src/raytracer/lights/ambientLight.cpp.o
.PHONY : src/raytracer/lights/ambientLight.o

# target to build an object file
src/raytracer/lights/ambientLight.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/beton.dir/build.make CMakeFiles/beton.dir/src/raytracer/lights/ambientLight.cpp.o
.PHONY : src/raytracer/lights/ambientLight.cpp.o

src/raytracer/lights/ambientLight.i: src/raytracer/lights/ambientLight.cpp.i
.PHONY : src/raytracer/lights/ambientLight.i

# target to preprocess a source file
src/raytracer/lights/ambientLight.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/beton.dir/build.make CMakeFiles/beton.dir/src/raytracer/lights/ambientLight.cpp.i
.PHONY : src/raytracer/lights/ambientLight.cpp.i

src/raytracer/lights/ambientLight.s: src/raytracer/lights/ambientLight.cpp.s
.PHONY : src/raytracer/lights/ambientLight.s

# target to generate assembly for a file
src/raytracer/lights/ambientLight.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/beton.dir/build.make CMakeFiles/beton.dir/src/raytracer/lights/ambientLight.cpp.s
.PHONY : src/raytracer/lights/ambientLight.cpp.s

src/raytracer/lights/directionalLight.o: src/raytracer/lights/directionalLight.cpp.o
.PHONY : src/raytracer/lights/directionalLight.o

# target to build an object file
src/raytracer/lights/directionalLight.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/beton.dir/build.make CMakeFiles/beton.dir/src/raytracer/lights/directionalLight.cpp.o
.PHONY : src/raytracer/lights/directionalLight.cpp.o

src/raytracer/lights/directionalLight.i: src/raytracer/lights/directionalLight.cpp.i
.PHONY : src/raytracer/lights/directionalLight.i

# target to preprocess a source file
src/raytracer/lights/directionalLight.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/beton.dir/build.make CMakeFiles/beton.dir/src/raytracer/lights/directionalLight.cpp.i
.PHONY : src/raytracer/lights/directionalLight.cpp.i

src/raytracer/lights/directionalLight.s: src/raytracer/lights/directionalLight.cpp.s
.PHONY : src/raytracer/lights/directionalLight.s

# target to generate assembly for a file
src/raytracer/lights/directionalLight.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/beton.dir/build.make CMakeFiles/beton.dir/src/raytracer/lights/directionalLight.cpp.s
.PHONY : src/raytracer/lights/directionalLight.cpp.s

src/raytracer/lights/pointLight.o: src/raytracer/lights/pointLight.cpp.o
.PHONY : src/raytracer/lights/pointLight.o

# target to build an object file
src/raytracer/lights/pointLight.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/beton.dir/build.make CMakeFiles/beton.dir/src/raytracer/lights/pointLight.cpp.o
.PHONY : src/raytracer/lights/pointLight.cpp.o

src/raytracer/lights/pointLight.i: src/raytracer/lights/pointLight.cpp.i
.PHONY : src/raytracer/lights/pointLight.i

# target to preprocess a source file
src/raytracer/lights/pointLight.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/beton.dir/build.make CMakeFiles/beton.dir/src/raytracer/lights/pointLight.cpp.i
.PHONY : src/raytracer/lights/pointLight.cpp.i

src/raytracer/lights/pointLight.s: src/raytracer/lights/pointLight.cpp.s
.PHONY : src/raytracer/lights/pointLight.s

# target to generate assembly for a file
src/raytracer/lights/pointLight.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/beton.dir/build.make CMakeFiles/beton.dir/src/raytracer/lights/pointLight.cpp.s
.PHONY : src/raytracer/lights/pointLight.cpp.s

src/raytracer/main.o: src/raytracer/main.cpp.o
.PHONY : src/raytracer/main.o

# target to build an object file
src/raytracer/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/beton.dir/build.make CMakeFiles/beton.dir/src/raytracer/main.cpp.o
.PHONY : src/raytracer/main.cpp.o

src/raytracer/main.i: src/raytracer/main.cpp.i
.PHONY : src/raytracer/main.i

# target to preprocess a source file
src/raytracer/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/beton.dir/build.make CMakeFiles/beton.dir/src/raytracer/main.cpp.i
.PHONY : src/raytracer/main.cpp.i

src/raytracer/main.s: src/raytracer/main.cpp.s
.PHONY : src/raytracer/main.s

# target to generate assembly for a file
src/raytracer/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/beton.dir/build.make CMakeFiles/beton.dir/src/raytracer/main.cpp.s
.PHONY : src/raytracer/main.cpp.s

src/raytracer/objects/sphere.o: src/raytracer/objects/sphere.cpp.o
.PHONY : src/raytracer/objects/sphere.o

# target to build an object file
src/raytracer/objects/sphere.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/beton.dir/build.make CMakeFiles/beton.dir/src/raytracer/objects/sphere.cpp.o
.PHONY : src/raytracer/objects/sphere.cpp.o

src/raytracer/objects/sphere.i: src/raytracer/objects/sphere.cpp.i
.PHONY : src/raytracer/objects/sphere.i

# target to preprocess a source file
src/raytracer/objects/sphere.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/beton.dir/build.make CMakeFiles/beton.dir/src/raytracer/objects/sphere.cpp.i
.PHONY : src/raytracer/objects/sphere.cpp.i

src/raytracer/objects/sphere.s: src/raytracer/objects/sphere.cpp.s
.PHONY : src/raytracer/objects/sphere.s

# target to generate assembly for a file
src/raytracer/objects/sphere.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/beton.dir/build.make CMakeFiles/beton.dir/src/raytracer/objects/sphere.cpp.s
.PHONY : src/raytracer/objects/sphere.cpp.s

src/raytracer/world.o: src/raytracer/world.cpp.o
.PHONY : src/raytracer/world.o

# target to build an object file
src/raytracer/world.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/beton.dir/build.make CMakeFiles/beton.dir/src/raytracer/world.cpp.o
.PHONY : src/raytracer/world.cpp.o

src/raytracer/world.i: src/raytracer/world.cpp.i
.PHONY : src/raytracer/world.i

# target to preprocess a source file
src/raytracer/world.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/beton.dir/build.make CMakeFiles/beton.dir/src/raytracer/world.cpp.i
.PHONY : src/raytracer/world.cpp.i

src/raytracer/world.s: src/raytracer/world.cpp.s
.PHONY : src/raytracer/world.s

# target to generate assembly for a file
src/raytracer/world.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/beton.dir/build.make CMakeFiles/beton.dir/src/raytracer/world.cpp.s
.PHONY : src/raytracer/world.cpp.s

src/rtx/color/color.o: src/rtx/color/color.cpp.o
.PHONY : src/rtx/color/color.o

# target to build an object file
src/rtx/color/color.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/beton.dir/build.make CMakeFiles/beton.dir/src/rtx/color/color.cpp.o
.PHONY : src/rtx/color/color.cpp.o

src/rtx/color/color.i: src/rtx/color/color.cpp.i
.PHONY : src/rtx/color/color.i

# target to preprocess a source file
src/rtx/color/color.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/beton.dir/build.make CMakeFiles/beton.dir/src/rtx/color/color.cpp.i
.PHONY : src/rtx/color/color.cpp.i

src/rtx/color/color.s: src/rtx/color/color.cpp.s
.PHONY : src/rtx/color/color.s

# target to generate assembly for a file
src/rtx/color/color.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/beton.dir/build.make CMakeFiles/beton.dir/src/rtx/color/color.cpp.s
.PHONY : src/rtx/color/color.cpp.s

src/rtx/color/screen.o: src/rtx/color/screen.cpp.o
.PHONY : src/rtx/color/screen.o

# target to build an object file
src/rtx/color/screen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/beton.dir/build.make CMakeFiles/beton.dir/src/rtx/color/screen.cpp.o
.PHONY : src/rtx/color/screen.cpp.o

src/rtx/color/screen.i: src/rtx/color/screen.cpp.i
.PHONY : src/rtx/color/screen.i

# target to preprocess a source file
src/rtx/color/screen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/beton.dir/build.make CMakeFiles/beton.dir/src/rtx/color/screen.cpp.i
.PHONY : src/rtx/color/screen.cpp.i

src/rtx/color/screen.s: src/rtx/color/screen.cpp.s
.PHONY : src/rtx/color/screen.s

# target to generate assembly for a file
src/rtx/color/screen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/beton.dir/build.make CMakeFiles/beton.dir/src/rtx/color/screen.cpp.s
.PHONY : src/rtx/color/screen.cpp.s

src/rtx/ray/ray.o: src/rtx/ray/ray.cpp.o
.PHONY : src/rtx/ray/ray.o

# target to build an object file
src/rtx/ray/ray.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/beton.dir/build.make CMakeFiles/beton.dir/src/rtx/ray/ray.cpp.o
.PHONY : src/rtx/ray/ray.cpp.o

src/rtx/ray/ray.i: src/rtx/ray/ray.cpp.i
.PHONY : src/rtx/ray/ray.i

# target to preprocess a source file
src/rtx/ray/ray.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/beton.dir/build.make CMakeFiles/beton.dir/src/rtx/ray/ray.cpp.i
.PHONY : src/rtx/ray/ray.cpp.i

src/rtx/ray/ray.s: src/rtx/ray/ray.cpp.s
.PHONY : src/rtx/ray/ray.s

# target to generate assembly for a file
src/rtx/ray/ray.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/beton.dir/build.make CMakeFiles/beton.dir/src/rtx/ray/ray.cpp.s
.PHONY : src/rtx/ray/ray.cpp.s

src/rtx/vec3/vec3.o: src/rtx/vec3/vec3.cpp.o
.PHONY : src/rtx/vec3/vec3.o

# target to build an object file
src/rtx/vec3/vec3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/beton.dir/build.make CMakeFiles/beton.dir/src/rtx/vec3/vec3.cpp.o
.PHONY : src/rtx/vec3/vec3.cpp.o

src/rtx/vec3/vec3.i: src/rtx/vec3/vec3.cpp.i
.PHONY : src/rtx/vec3/vec3.i

# target to preprocess a source file
src/rtx/vec3/vec3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/beton.dir/build.make CMakeFiles/beton.dir/src/rtx/vec3/vec3.cpp.i
.PHONY : src/rtx/vec3/vec3.cpp.i

src/rtx/vec3/vec3.s: src/rtx/vec3/vec3.cpp.s
.PHONY : src/rtx/vec3/vec3.s

# target to generate assembly for a file
src/rtx/vec3/vec3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/beton.dir/build.make CMakeFiles/beton.dir/src/rtx/vec3/vec3.cpp.s
.PHONY : src/rtx/vec3/vec3.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... beton"
	@echo "... src/raytracer/camera.o"
	@echo "... src/raytracer/camera.i"
	@echo "... src/raytracer/camera.s"
	@echo "... src/raytracer/lights/ambientLight.o"
	@echo "... src/raytracer/lights/ambientLight.i"
	@echo "... src/raytracer/lights/ambientLight.s"
	@echo "... src/raytracer/lights/directionalLight.o"
	@echo "... src/raytracer/lights/directionalLight.i"
	@echo "... src/raytracer/lights/directionalLight.s"
	@echo "... src/raytracer/lights/pointLight.o"
	@echo "... src/raytracer/lights/pointLight.i"
	@echo "... src/raytracer/lights/pointLight.s"
	@echo "... src/raytracer/main.o"
	@echo "... src/raytracer/main.i"
	@echo "... src/raytracer/main.s"
	@echo "... src/raytracer/objects/sphere.o"
	@echo "... src/raytracer/objects/sphere.i"
	@echo "... src/raytracer/objects/sphere.s"
	@echo "... src/raytracer/world.o"
	@echo "... src/raytracer/world.i"
	@echo "... src/raytracer/world.s"
	@echo "... src/rtx/color/color.o"
	@echo "... src/rtx/color/color.i"
	@echo "... src/rtx/color/color.s"
	@echo "... src/rtx/color/screen.o"
	@echo "... src/rtx/color/screen.i"
	@echo "... src/rtx/color/screen.s"
	@echo "... src/rtx/ray/ray.o"
	@echo "... src/rtx/ray/ray.i"
	@echo "... src/rtx/ray/ray.s"
	@echo "... src/rtx/vec3/vec3.o"
	@echo "... src/rtx/vec3/vec3.i"
	@echo "... src/rtx/vec3/vec3.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

